name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - streamlit
    - joblib
    - numpy
    - pandas
    - shap
    - matplotlib
    - scikit-learn==1.5.1