name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - scikit-learn=1.5.2
  - streamlit=1.39.0
  - joblib=1.4.2
  - numpy
  - pandas=2.2.3
  - shap=0.45.1
  - matplotlib=3.9.2
  - ipython=8.18.1
  - pip
  - pip:
    - streamlit
