name: myenv
channels:
  - defaults
dependencies:
  - python
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - openpyxl
  - tabulate
  - scikit-optimize 
  - imbalanced-learn
  - pip
  - xgboost
  - lightgbm
  - joblib
  - pip:
    - streamlit
