name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - scikit-learn=1.5.2
  - streamlit=1.39.0
  - joblib=1.4.2
  - numpy=1.26.4
  - pandas=2.2.3
  - shap
  - matplotlib
  - ipython
  - pip
  - pip:
    - streamlit
